### ISSUE TITLE
Can not change port - linux

### ISSUE THREAD

**Issue by cpantel** [ernesto-g/educiaa_python_editor#4]
There is no dialog to change the port. The steps are "EDUCIAA"->Configuration

EDU-CIAA Python Editor 1.2
https://github.com/ernesto-g/educiaa_python_editor
Editor based on EDILE 0.2 http://edile.googlecode.com 
read from file:ttyUSB0
Traceback (most recent call last):
  File "ciaa_plugin.py", line 70, in item_Configuration
  File "ConfigWindow.py", line 35, in **init**
  File "dist-packages/serial/tools/list_ports_posix.py", line 122, in comports
  File "dist-packages/serial/tools/list_ports_posix.py", line 93, in describe
  File "dist-packages/serial/tools/list_ports_posix.py", line 80, in usb_lsusb_string
NameError: global name 'base' is not defined

The communication with the board is fine. With the same user I've downloaded quite a lot of programs and debugged them.

**Comment by ernesto-g** [comment]
This is a bug from py-serial library : https://github.com/pyserial/pyserial/issues/135. I put a try-catch block in between that line in 1.3 version (branch "testing" for now)
